import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Samita</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>Samita</h1>
    </div>
  )
}

export default Home
