import { Flex, Text } from "@chakra-ui/layout";
import type { NextPage } from "next";
import Head from "next/head";

const About: NextPage = () => {
  return (
    <Flex
      w="100%"
      h="100%"
      bg="green.200"
      justifyContent="center"
      alignItems="center"
    >
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Text>About</Text>
    </Flex>
  );
};

export default About;
