import { Flex, Text } from "@chakra-ui/layout";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <Flex
      w="100%"
      h="100%"
      bg="orange.200"
      justifyContent="center"
      alignItems="center"
    >
      <Head>
        <title>Samita</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Text>Samita</Text>
    </Flex>
  );
};

export default Home;
